# Generated by Django 5.2.1 on 2025-09-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress')], default='Pending', max_length=50)),
                ('category', models.CharField(blank=True, choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Urgent', 'Urgent')], max_length=100, null=True)),
            ],
        ),
    ]
