# Generated by Django 5.2.1 on 2025-09-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Urgent', 'Urgent')], default='Work', max_length=100, null=True),
        ),
    ]
